### ISSUE TITLE
please, release tag 

### ISSUE THREAD

**Issue by sasezaki** [yoya/IO_Bit#2]
#1 で HEAD上はcomposer.json新しくなりましたが、リリースタグを切っていないので、現行IO_MIDIをcomposer requireしたときに、
`PHP Warning:  require_once(IO/Bit.php): failed to open stream: No such file or directory `
になるので、新しくリリースタグ`2.1.2`を切ってください

**Comment by yoya** [comment]
御意！ openpear の方が最新 2.1.2 なのでマージするまでお待ち下さい。

**Comment by yoya** [comment]
2.1.2 タグ打ちました。

**Comment by sasezaki** [comment]
thanks!
